In [ ]:
import torch
import os

### 线性代数的一些相关的操作和知识

In [ ]:
# 转置
A = torch.arange(9,dtype=torch.float32).reshape(3,3)
A , A.T , A.shape, type(A.shape[0]) ,type(A.shape) , type(torch.Size)

In [ ]:
B = torch.arange(24).reshape(2,3,4)
B

In [ ]:
A.mean() , A.sum()/A.numel()

In [ ]:
A.mean(axis=0) , A.sum(axis=0)/A.shape[0] # 这里的求和会直接丢掉其他的维度

In [ ]:
A.mean(axis=0,keepdims=True)

#### 点积 
两个相同大小的向量进行各项的相乘最后结果进行求和 -- **只能对于向量来说**
对于多维的不行了

In [33]:
y = torch.ones(4,dtype=torch.float32)
x = torch.arange(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [ ]:
torch.sum(x * y) # 和上面的效果是一样的

tensor(6.)

In [ ]:
my = torch.ones(6,dtype=torch.float32).reshape(2,3)
mx = torch.arange(6,dtype=torch.float32).reshape(2,3)
mx,my,torch.dot(mx,my)

In [45]:
A = torch.arange(12,dtype=torch.float32).reshape(4,3)
x = torch.ones(3,dtype=torch.float32)
A,x,A.shape,x.shape, torch.mv(A,x) # mv是使用matrix*vector

(tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([1., 1., 1.]),
 torch.Size([4, 3]),
 torch.Size([3]),
 tensor([ 3., 12., 21., 30.]))

In [50]:
B = torch.arange(12,dtype=torch.float32).reshape(3,4)
torch.mm(A,B) , A,B

(tensor([[ 20.,  23.,  26.,  29.],
         [ 56.,  68.,  80.,  92.],
         [ 92., 113., 134., 155.],
         [128., 158., 188., 218.]]),
 tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

#### 范数
L2范数是向量元素平方和的平方根-- $||x_2|| = \sqrt{\sum\limits_{i=1}^n{x_i^2}}$

L1范数每个元素的绝对值求和-- $||x||_1 = \sum\limits_{i=1}^n{|x_i|}$

矩阵的F范数是矩阵元素的平方和的平方根-- $||X||_F = \sqrt{\sum\limits_{i=1}^m\sum\limits_{j=1}^n{x_{ij}^2}}$

In [58]:
u = torch.tensor([3.0,-4.0])
m = torch.tensor([[3.0,4.0],[5.0,6.0]])
u.norm() , torch.norm(u) , torch.abs(u).sum(),m.norm(),torch.norm(m)

(tensor(5.), tensor(5.), tensor(7.), tensor(9.2736), tensor(9.2736))

### axis理解

In [62]:
test = torch.ones(24,dtype=torch.float32).reshape(2,3,4)
test, test.sum(axis=0) , test.sum(axis=1) , test.sum(axis=2)

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[4., 4., 4.],
         [4., 4., 4.]]))

In [67]:
# 如果这里是keepdims的话只是把对应的维度变成了1
a = test.sum(axis=0,keepdims=True)
b = test.sum(axis=1,keepdims=True) 
c = test.sum(axis=2,keepdims=True)
a,b,c,a.shape,b.shape,c.shape

(tensor([[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]]),
 tensor([[[3., 3., 3., 3.]],
 
         [[3., 3., 3., 3.]]]),
 tensor([[[4.],
          [4.],
          [4.]],
 
         [[4.],
          [4.],
          [4.]]]),
 torch.Size([1, 3, 4]),
 torch.Size([2, 1, 4]),
 torch.Size([2, 3, 1]))

In [ ]:
# 也是可以对多个维度进行求和的
aa = test.sum(axis=[0,1],keepdims=True)
aa

tensor([[[6., 6., 6., 6.]]])