### 连续求导的学习

In [1]:
import torch 
x = torch.arange(4,dtype=torch.float32,requires_grad=True) # 加上requires_grad就可以随时看到x的梯度
x,x.grad

/Users/fac/Code/Lab/DL/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [2]:
y = 2 * torch.dot(x,x) # 这里是内积使用每一项项城相加 == y = sum(x*x)
y

tensor(28., grad_fn=<MulBackward0>)

In [3]:
y.backward()
x.grad # 查看y每次求导对应的x的梯度

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad.zero_() # 梯度清零 
z = x.sum()
z.backward()
x.grad

tensor([1., 1., 1., 1.])