In [2]:
import torch

### 创建张量的常用的方式

In [ ]:
x = torch.arange(12)
x

12

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [8]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [5]:
x = torch.tensor([[1,2,3,4,5],[1,2,3,4,5]])
y = torch.tensor([[1,2,3,4,5],[1,2,3,4,5]])
x+y,x-y,x*y,x/y,x**y

(tensor([[ 2,  4,  6,  8, 10],
         [ 2,  4,  6,  8, 10]]),
 tensor([[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]),
 tensor([[ 1,  4,  9, 16, 25],
         [ 1,  4,  9, 16, 25]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[   1,    4,   27,  256, 3125],
         [   1,    4,   27,  256, 3125]]))

### 将多个张量连接起来

In [9]:
x = torch.arange(12,dtype=torch.float32).reshape(3,4)
y = torch.tensor([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
torch.cat((x,y),dim=0), torch.cat((x,y),dim=1) # dimensino维度:0的话按照行,1按照列

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 2.,  3.,  4.,  5.],
         [ 3.,  4.,  5.,  6.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  5.],
         [ 8.,  9., 10., 11.,  3.,  4.,  5.,  6.]]))

In [10]:
x.sum()

tensor(66.)

### 广播机制

In [11]:
x = torch.arange(3).reshape(1,3)
y = torch.arange(2).reshape(2,1)
x,y,x+y

(tensor([[0, 1, 2]]),
 tensor([[0],
         [1]]),
 tensor([[0, 1, 2],
         [1, 2, 3]]))

### 内存问题
使用[:]

In [8]:
# 错误操作
Y = torch.arange(12,dtype=torch.float32).reshape(3,4)
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
before = id(Y) # Y的地址
Y = Y+X
before,id(Y) ,before==id(Y) #发现两个不一样

(1278575972080, 1278376400416, False)

In [ ]:
# 正确操作
Z = torch.zeros_like(Y)
print("before id: ",id(Z))
Z[:] = X+Y #必须要使用[:]才能够正确的操作
print("before id: ",id(Z))

before id:  1278575870336
before id:  1278575571840
